name: "🏆 Project Priority Order"
description: "Defines the priority ranking of all projects (managed by report owner)"
title: "🏆 Project Priority Order"
labels: ["priority-order"]
body:
  - type: markdown
    attributes:
      value: |
        ## How to use this issue
        
        List project names below in priority order (line 1 = highest priority).
        Edit this issue to reorder priorities. The dashboard will update automatically.
        
        **Only the report owner should edit this issue.**
  - type: textarea
    id: priority-list
    attributes:
      label: Priority Order
      description: "One project name per line, in priority order (1 = highest). Must match the issue title exactly (without the 📊 emoji prefix)."
      value: |
        TypeSpec Evolution
        Azure SDK AI Agent Integration
        SDK Performance Improvements
        Python SDK Async Overhaul
        AutoRest Deprecation
        Azure MCP
        Azure SDK Skills
        GitHub Copilot for Azure
        Azure SDK Tools Agent
        API View Copilot
        Java vNext (Unbranded Core)
        Engineering System (EngSys)
    validations:
      required: true
