name: "📊 Project Status Update"
description: "Submit a status update for your project"
title: "Status Update: "
labels: ["status-update"]
body:
  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Which project are you updating?
      options:
        - TypeSpec Evolution
        - Azure SDK AI Agent Integration
        - SDK Performance Improvements
        - Python SDK Async Overhaul
        - AutoRest Deprecation
        - Azure MCP
        - Azure SDK Skills
        - GitHub Copilot for Azure
        - Azure SDK Tools Agent
        - API View Copilot
        - Java vNext (Unbranded Core)
        - Engineering System (EngSys)
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      options:
        - on-track
        - at-risk
        - needs-attention
    validations:
      required: true
  - type: textarea
    id: value-delivered
    attributes:
      label: Value Delivered
      description: "Features released, milestones hit, customer value shipped (one per line)"
      placeholder: "- Feature X shipped to preview\n- Milestone Y completed"
  - type: textarea
    id: impacts
    attributes:
      label: Customer Impacts
      description: "How has recent work affected customers? (one per line)"
      placeholder: "- Reduced latency by 30% for Storage users"
  - type: textarea
    id: risks
    attributes:
      label: Blockers & Risks
      description: "What's blocking progress or at risk? (one per line)"
      placeholder: "- Blocked on partner team alignment"
  - type: textarea
    id: help-needed
    attributes:
      label: Help Needed
      description: "Specific asks for leadership (one per line)"
      placeholder: "- Need executive support for cross-team alignment"
  - type: textarea
    id: milestones
    attributes:
      label: Upcoming Milestones
      description: "Key milestones with dates and status (one per line: name | date | status)"
      placeholder: "Public Preview | 2026-05-15 | planned\nGA Release | 2026-08-01 | planned"
